import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from '@app/providers';
import { ReactNode } from 'react';
import "./globals.css";

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: ReactNode; }>) {
  return (
    <html lang="en" className='dark'>
      <body
        className={`${inter.className} antialiased bg-black text-white`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}