import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from 'next/font/google'
import { Providers } from '@/app/Providers';
import { Toaster } from 'react-hot-toast';
import NextTopLoader from 'nextjs-toploader';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body
        className={`antialiased`}
      >
        <NextTopLoader
          template='<div class="bar" role="bar"><div class="peg"></div></div>'
          color={'#3ad151'}
        />
        <Toaster/>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
